project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "SP500"
  author:
    - Sicheng Wang (sw3868)
    - Shuai He (sh4225)
  repo-url: https://github.com/Sicheng-Wang1999/SP500
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


